package main

import "math/bits"

// The piece RNG. Every peer derives the same deterministic 7-bag sequence from
// GameMeta.Seed, so all boards spawn identical pieces without any coordination.
// This reproduces Go's math/rand/v2 PCG + Fisher-Yates shuffle bit for bit; the
// sequence is seekable — bag k is generated by PCG(seed, k), so any global
// piece index is reachable in O(1) bags. (See example-python/agent.py for the
// same routine in Python, and internal/rng in the repo for the original.)

// pcg is the 128-bit PCG-XSL-RR state math/rand/v2 uses.
type pcg struct{ hi, lo uint64 }

// next advances the generator and returns the next 64-bit output.
func (p *pcg) next() uint64 {
	const mulHi, mulLo = 2549297995355413924, 4865540595714422341
	const incHi, incLo = 6364136223846793005, 1442695040888963407
	hi, lo := bits.Mul64(p.lo, mulLo)
	hi += p.hi*mulLo + p.lo*mulHi
	var carry uint64
	lo, carry = bits.Add64(lo, incLo, 0)
	hi = hi + incHi + carry
	p.lo, p.hi = lo, hi
	out := hi
	out ^= out >> 32
	out *= 0xDA942042E4DD58B5
	out ^= out >> 48
	out *= lo | 1
	return out
}

// uint64n returns a uniform value in [0, n) using Lemire's method, matching
// rand/v2's Uint64N exactly (the power-of-two fast path and the biased-low
// rejection threshold included).
func (p *pcg) uint64n(n uint64) uint64 {
	if n&(n-1) == 0 { // power of two
		return p.next() & (n - 1)
	}
	hi, lo := bits.Mul64(p.next(), n)
	if lo < n {
		thresh := -n % n
		for lo < thresh {
			hi, lo = bits.Mul64(p.next(), n)
		}
	}
	return hi
}

// pieceAt returns the piece type (0..6) at the given global sequence index: the
// index's position within its 7-bag, drawn from a Fisher-Yates shuffle of that
// bag seeded by PCG(seed, bagNumber).
func pieceAt(seed uint64, index int) int {
	bag, pos := index/7, index%7
	p := &pcg{hi: seed, lo: uint64(bag)}
	b := [7]int{0, 1, 2, 3, 4, 5, 6}
	for i := 6; i > 0; i-- {
		j := p.uint64n(uint64(i + 1))
		b[i], b[j] = b[j], b[i]
	}
	return b[pos]
}
