package main

import "testing"

// TestPieceParity pins the piece sequence against values generated by the
// repo's Go rng package (internal/rng) — the same fixtures example-python's
// selftest uses. If these match, golang-mk1 spawns exactly what every other
// peer does, which is the whole contract.
func TestPieceParity(t *testing.T) {
	expected := map[uint64][]int{
		42:    {2, 3, 4, 1, 0, 5, 6, 6, 0, 5, 4, 2, 3, 1, 2, 1, 4, 3, 6, 5, 0},
		12345: {6, 3, 2, 1, 0, 4, 5, 0, 1, 5, 3, 2, 6, 4, 3, 6, 4, 2, 5, 1, 0},
	}
	for seed, want := range expected {
		for i, w := range want {
			if got := pieceAt(seed, i); got != w {
				t.Fatalf("seed %d index %d: piece = %d, want %d", seed, i, got, w)
			}
		}
		// Each 7-bag is a permutation of the seven pieces.
		var seen [7]bool
		for i := 0; i < 7; i++ {
			seen[pieceAt(seed, i)] = true
		}
		for pt, ok := range seen {
			if !ok {
				t.Fatalf("seed %d: first bag missing piece %d", seed, pt)
			}
		}
	}
}

// TestPieceCells spot-checks geometry: the I piece spawned at (2,3) fills the
// row-3 horizontal, matching example-python's selftest.
func TestPieceCells(t *testing.T) {
	got := pieceCells(0, 0, 2, 3)
	want := [4]cell{{3, 3}, {3, 4}, {3, 5}, {3, 6}}
	if got != want {
		t.Fatalf("I spawn cells = %v, want %v", got, want)
	}
}
