package main

import "testing"

// TestPieceParity pins the piece sequence against values generated by the
// repo's Go rng package (internal/rng) — the same fixtures example-python's
// selftest uses. If these match, golang-mk1 spawns exactly what every other
// peer does, which is the whole contract.
func TestPieceParity(t *testing.T) {
	expected := map[uint64][]int{
		42:    {2, 3, 4, 1, 0, 5, 6, 6, 0, 5, 4, 2, 3, 1, 2, 1, 4, 3, 6, 5, 0},
		12345: {6, 3, 2, 1, 0, 4, 5, 0, 1, 5, 3, 2, 6, 4, 3, 6, 4, 2, 5, 1, 0},
	}
	for seed, want := range expected {
		for i, w := range want {
			if got := pieceAt(seed, i); got != w {
				t.Fatalf("seed %d index %d: piece = %d, want %d", seed, i, got, w)
			}
		}
		// Each 7-bag is a permutation of the seven pieces.
		var seen [7]bool
		for i := 0; i < 7; i++ {
			seen[pieceAt(seed, i)] = true
		}
		for pt, ok := range seen {
			if !ok {
				t.Fatalf("seed %d: first bag missing piece %d", seed, pt)
			}
		}
	}
}

// TestPieceCells spot-checks geometry: the I piece spawned at (2,3) fills the
// row-3 horizontal, matching example-python's selftest.
func TestPieceCells(t *testing.T) {
	got := pieceCells(0, 0, 2, 3)
	want := [4]cell{{3, 3}, {3, 4}, {3, 5}, {3, 6}}
	if got != want {
		t.Fatalf("I spawn cells = %v, want %v", got, want)
	}
}

// TestSplitParity pins the teams-mode piece SPLIT (meta split_pieces) against
// values generated by the repo's Go rng package (internal/rng: PieceSets and
// NewSet), exactly as TestPieceParity pins the 7-bag. Two peers that disagree
// about the deal disagree about what each seat may spawn, so this is the same
// whole contract one step further in: the hands AND the sequence each hand
// draws.
func TestSplitParity(t *testing.T) {
	type fixture struct {
		seed  uint64
		seats int
		sets  [][]int
		seqs  [][]int // the first 12 pieces of each slot's sequence
	}
	for _, f := range []fixture{
		{42, 2,
			[][]int{{0, 1, 4}, {2, 3, 5, 6}},
			[][]int{{0, 4, 1, 1, 4, 0, 4, 1, 0, 1, 0, 4}, {3, 5, 6, 2, 6, 2, 3, 5, 5, 3, 2, 6}}},
		{42, 3,
			[][]int{{0, 4, 5}, {2, 3}, {1, 6}},
			[][]int{{5, 4, 0, 0, 5, 4, 4, 0, 5, 0, 5, 4}, {3, 2, 3, 2, 2, 3, 2, 3, 2, 3, 2, 3}, {1, 6, 6, 1, 6, 1, 1, 6, 1, 6, 1, 6}}},
		{42, 7,
			[][]int{{5}, {0}, {6}, {1}, {4}, {3}, {2}},
			nil},
		{12345, 2,
			[][]int{{0, 1, 2, 5}, {3, 4, 6}},
			[][]int{{5, 0, 2, 1, 0, 5, 1, 2, 5, 2, 0, 1}, {4, 6, 3, 6, 4, 3, 3, 6, 4, 6, 4, 3}}},
		{12345, 3,
			[][]int{{1, 2}, {0, 5, 6}, {3, 4}},
			[][]int{{2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2}, {5, 0, 6, 6, 5, 0, 6, 5, 0, 5, 6, 0}, {3, 4, 4, 3, 3, 4, 4, 3, 4, 3, 4, 3}}},
		{12345, 9,
			[][]int{{1}, {3}, {4}, {6}, {2}, {0}, {5}, {1}, {4}},
			nil},
	} {
		got := pieceSets(f.seed, f.seats)
		if len(got) != len(f.sets) {
			t.Fatalf("seed %d, %d seats: %d sets, want %d", f.seed, f.seats, len(got), len(f.sets))
		}
		for slot, want := range f.sets {
			if len(got[slot]) != len(want) {
				t.Fatalf("seed %d, %d seats: slot %d = %v, want %v", f.seed, f.seats, slot, got[slot], want)
			}
			for i := range want {
				if got[slot][i] != want[i] {
					t.Fatalf("seed %d, %d seats: slot %d = %v, want %v", f.seed, f.seats, slot, got[slot], want)
				}
			}
			// pieceSetFor is the accessor the game itself uses.
			if ration := pieceSetFor(f.seed, f.seats, slot); len(ration) != len(want) {
				t.Errorf("seed %d, %d seats: pieceSetFor(slot %d) = %v, want %v", f.seed, f.seats, slot, ration, want)
			}
		}
		for slot, want := range f.seqs {
			for i, w := range want {
				if pt := pieceAtIn(f.seed, got[slot], i); pt != w {
					t.Errorf("seed %d, %d seats, slot %d: piece %d = %d, want %d", f.seed, f.seats, slot, i, pt, w)
				}
			}
		}
	}
}

// TestSplitCoversTheBag: whatever the seed and however many seats, every one
// of the seven types is dealt to somebody and no seat is left empty-handed —
// the team still has the whole bag between them (gameplays §5).
func TestSplitCoversTheBag(t *testing.T) {
	for seats := 1; seats <= 12; seats++ {
		for _, seed := range []uint64{1, 42, 12345, 999999} {
			var seen [7]bool
			for slot, set := range pieceSets(seed, seats) {
				if len(set) == 0 {
					t.Errorf("seed %d, %d seats: slot %d was dealt nothing", seed, seats, slot)
				}
				for _, pt := range set {
					seen[pt] = true
				}
			}
			for pt, ok := range seen {
				if !ok {
					t.Errorf("seed %d, %d seats: nobody holds piece %d", seed, seats, pt)
				}
			}
		}
	}
}

// TestBagParity pins the bag rule (meta bag) against values generated by the
// repo's Go rng package (internal/rng: NewBag under the double bag and no
// bag, over the seven types and over a split-pieces ration), exactly as
// TestPieceParity pins the 7-bag and TestSplitParity the split. Two peers
// that deal the same seed differently spawn different pieces, so this is the
// same whole contract one kind further.
func TestBagParity(t *testing.T) {
	full := map[string]map[uint64][]int{
		bagDouble: {
			42:    {6, 5, 2, 3, 0, 3, 2, 4, 1, 4, 0, 1, 6, 5, 4, 5, 4, 1, 3, 1, 3, 6, 0, 2, 5, 6, 0, 2},
			12345: {3, 5, 4, 0, 3, 0, 6, 1, 6, 1, 5, 2, 2, 4, 4, 4, 1, 1, 0, 2, 0, 3, 5, 6, 6, 5, 3, 2},
		},
		bagNone: {
			42:    {6, 1, 0, 4, 1, 2, 2, 5, 4, 6, 6, 5, 0, 0, 5, 0, 3, 0, 0, 0, 0},
			12345: {5, 4, 0, 5, 5, 0, 2, 1, 4, 4, 1, 6, 2, 1, 5, 2, 1, 6, 5, 5, 5},
		},
	}
	for kind, bySeed := range full {
		for seed, want := range bySeed {
			for i, w := range want {
				if got := pieceAtBag(seed, nil, kind, i); got != w {
					t.Fatalf("bag %q seed %d index %d: piece = %d, want %d", kind, seed, i, got, w)
				}
			}
		}
	}
	// Every fourteen of a double bag are two of each type.
	for i := 0; i < 42; i += 14 {
		var count [7]int
		for j := 0; j < 14; j++ {
			count[pieceAtBag(42, nil, bagDouble, i+j)]++
		}
		for pt, n := range count {
			if n != 2 {
				t.Errorf("double bag %d holds piece %d %d times, want 2", i/14, pt, n)
			}
		}
	}
	// A ration under each kind: seed 42 dealt to two seats ({I O Z}, {T S J L}).
	sets := pieceSets(42, 2)
	rations := map[string][][]int{
		bagDouble: {{1, 0, 4, 1, 0, 4, 0, 4, 4, 1, 1, 0}, {6, 6, 5, 3, 3, 5, 2, 2, 6, 3, 5, 2}},
		bagNone:   {{1, 0, 0, 4, 1, 0, 1, 4, 1, 0, 4, 4}, {2, 5, 6, 2, 6, 2, 2, 2, 5, 3, 6, 3}},
	}
	for kind, bySlot := range rations {
		for slot, want := range bySlot {
			for i, w := range want {
				if got := pieceAtBag(42, sets[slot], kind, i); got != w {
					t.Errorf("bag %q ration %v index %d: piece = %d, want %d", kind, sets[slot], i, got, w)
				}
			}
		}
	}
	// The standard bag through pieceAtBag is pieceAt / pieceAtIn unchanged,
	// and an unknown kind reads as the standard bag, as the game reads it.
	for i := 0; i < 30; i++ {
		if pieceAtBag(42, nil, bagSingle, i) != pieceAt(42, i) || pieceAtBag(42, nil, "triple", i) != pieceAt(42, i) {
			t.Fatalf("index %d: the standard bag through pieceAtBag differs from pieceAt", i)
		}
		if pieceAtBag(42, sets[0], bagSingle, i) != pieceAtIn(42, sets[0], i) {
			t.Fatalf("index %d: a ration's standard bag through pieceAtBag differs from pieceAtIn", i)
		}
	}
}
